# Generated by Django 5.2.5 on 2025-12-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='rain_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
