# Generated by Django 5.2.5 on 2025-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_forecast_rain_probability_forecast_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='weather_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
